<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-B4ND95H" failures="0" tests="7" name="com.testNGScripts.TestNgExpectedException" time="5.030" errors="1" timestamp="2022-09-28T15:59:15 IST" skipped="0">
  <testcase classname="com.testNGScripts.TestNgExpectedException" name="test_invocation" time="0.002"/>
  <system-out/>
  <testcase classname="com.testNGScripts.TestNgExpectedException" name="test_invocation" time="0.002"/>
  <system-out/>
  <testcase classname="com.testNGScripts.TestNgExpectedException" name="test_invocation" time="0.003"/>
  <system-out/>
  <testcase classname="com.testNGScripts.TestNgExpectedException" name="test_invocation" time="0.002"/>
  <system-out/>
  <testcase classname="com.testNGScripts.TestNgExpectedException" name="test_invocation" time="0.002"/>
  <system-out/>
  <testcase classname="com.testNGScripts.TestNgExpectedException" name="test" time="0.013"/>
  <system-out/>
  <testcase classname="com.testNGScripts.TestNgExpectedException" name="test_timeout" time="5.006">
    <error message="Method com.testNGScripts.TestNgExpectedException.test_timeout() didn&#039;t finish within the time-out 5000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.testNGScripts.TestNgExpectedException.test_timeout() didn't finish within the time-out 5000
at java.base@11.0.13/java.lang.Thread.sleep(Native Method)
at app//com.testNGScripts.TestNgExpectedException.test_timeout(TestNgExpectedException.java:24)
at java.base@11.0.13/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@11.0.13/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base@11.0.13/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@11.0.13/java.lang.reflect.Method.invoke(Method.java:566)
at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:44)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:72)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:10)
at java.base@11.0.13/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@11.0.13/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base@11.0.13/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base@11.0.13/java.lang.Thread.run(Thread.java:834)
]]>
    </error>
  </testcase> <!-- test_timeout -->
  <system-out/>
</testsuite> <!-- com.testNGScripts.TestNgExpectedException -->
